catalogs:
  docusaurus:
    "@docusaurus/core": 3.10.1
    "@docusaurus/module-type-aliases": 3.10.1
    "@docusaurus/plugin-client-redirects": 3.10.1
    "@docusaurus/plugin-content-docs": 3.10.1
    "@docusaurus/plugin-content-pages": 3.10.1
    "@docusaurus/plugin-sitemap": 3.10.1
    "@docusaurus/plugin-svgr": 3.10.1
    "@docusaurus/theme-classic": 3.10.1
    "@docusaurus/theme-common": 3.10.1
    "@docusaurus/theme-live-codeblock": 3.10.1
    "@docusaurus/types": 3.10.1
  react:
    react: 19.2.7
    react-dom: 19.2.7

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmRegistryServer: "https://registry.npmjs.org/"
