/**
 * @typedef {import('@docusaurus/plugin-content-docs').SidebarsConfig} SidebarsConfig
 */

/** @type {SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
