on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: &actions-checkout actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: 'recursive'
      - run: corepack enable
      - uses: &actions-setup-node actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with: &setup-node-config
          node-version-file: 'package.json'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          path: build
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: *actions-checkout
      - run: corepack enable
      - uses: *actions-setup-node
        with: *setup-node-config
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: *actions-checkout
      - run: corepack enable
      - uses: *actions-setup-node
        with: *setup-node-config
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck
  a11y:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      # https://github.com/pa11y/pa11y/blob/2055ee510163d871e874f6ea0bfe895f84bbac4a/.github/workflows/tests.yml#L37
      - run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - uses: *actions-checkout
      - run: corepack enable
      - uses: *actions-setup-node
        with: *setup-node-config
      - run: pnpm install --frozen-lockfile
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          path: build
      - run: pnpm run a11y:ci
