name: Deploy

on:
  release:
    types:
      - 'published'
  workflow_dispatch:
    inputs:
      svgoVersion:
        description: The svg/svgo branch or tag to pull docs from.
        default: 'main'
        type: string

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: svg/svgo
          path: .svgo
          ref: ${{ inputs.svgoVersion }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
