name: CI

env:
  NODE: 22

on:
  - 'pull_request'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: svg/svgo
          path: .svgo
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE }}
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn run build
  lint:
    name: Lint and Check Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE }}
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn run qa
